language:    erlang
otp_release: 17.4
sudo:        false

before_script:
  - epmd -daemon
  - erl -name "detached@`hostname -f`" -detached
  - erl -name "rpckill@`hostname -f`" -detached

script:
  - ps wwaux
  - ./test_script.erl `hostname -f`
