language:    erlang
otp_release: 17.4
sudo:        false

before_script:
  - epmd -daemon
  - erl -sname "detached" -detached
  - erl -sname "rpckill" -detached

  - ps waux
  - cat `which erl`

script: ./test_script.erl
